name: Run tests and deploy

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Run static tests
        run: bundle exec rake static

      - name: Run ruby tests
        run: bundle exec rake test

  deploy:
    runs-on: ubuntu-18.04
    needs: test
    environment: rubygems

    # Only deploy if running on master
    if: github.ref == 'refs/heads/master'

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install semantic release
        run: npm install semantic-release semantic-release-rubygem

      - name: Run semantic release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GEM_HOST_API_KEY: ${{ secrets.GEM_HOST_API_KEY }}
        run: npx semantic-release
